version: '3.0'
services:
  app:
    image: jenkins/jenkins:lts
    container_name: jenkins-master
    restart: always
    ports:
      - "50000:50000"
      - "8091:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - app-data:/var/jenkins_home
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
      TZ: Asia/Tokyo
volumes:
  app-data:
