version: '3.1'
services:
    app:
        image: koda/docker-knowledge
        #build: .
        environment:
            - TZ=Asia/Tokyo
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - knowledge-app-data:/root/.knowledge
        ports:
            - "8085:8080"
        restart: always
        depends_on:
            - "db"
    db:
        image: postgres:9
        environment:
            - TZ=Asia/Tokyo
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=admin123
            - POSTGRES_DB=knowledge_production
        volumes:
            - /etc/localtime:/etc/localtime:ro
            #- ./volumes/initdb:/docker-entrypoint-initdb.d
            - knowledge-db-data:/var/lib/postgresql/data
        restart: always
volumes:
    knowledge-app-data:
    knowledge-db-data:
